### ISSUE TITLE
Remove drupal.org packaging script info

### ISSUE THREAD

**Issue by jenlampton** [bjoern-st/wordpress_import#1]
In the .info file there is information added by drupal.org which should be removed for the Backdrop version of the module:

```
; Information added by drupal.org packaging script on 2013-10-26
version = "1.x-1.x-dev"
backdrop = "1.x"
```

**Comment by bjoern-st** [comment]
Fixed .. please see https://github.com/bjoern-st/wordpress_import/commit/f16a24e3b518ca1d813007f50031581e1ed4ca5a
