### ISSUE TITLE
Interested in some help?

### ISSUE THREAD

**Issue by laryn** [bjoern-st/wordpress_import#10]
@bjoern-st I am using this module on a site and it's really great! I would like to offer some help to get some of the big breakers cleaned up and a new release to make sure this is more friendly to potential switchers from Wordpress. Would you be willing to take me on as a co-maintainer?

**Comment by bjoern-st** [comment]
Yes - of course. 
The most interesting point would be to change to form-state and get rid of the dependency ..

**Comment by laryn** [comment]
Thanks @bjoern-st ! I'll do some basic clean up for now so it works decently for people interested in coming over from Wordpress, and I've moved your idea into another thread:

https://github.com/backdrop-contrib/wordpress_import/issues/18

**Comment by laryn** [comment]
@bjoern-st Just a heads-up that I have invited @keiserjb to join as a maintainer as well. He is working on some further improvements and clean up.

**Comment by keiserjb** [comment]
Yes, I want to make it so the images imported from wp turn into managed files.

**Comment by laryn** [comment]
@keiserjb If you have time to test the latest release, please let me know how it goes -- images and files should turn into managed files now.

**Comment by keiserjb** [comment]
Fantastic, I may not get to it until next week.
