### ISSUE TITLE
Update docblock for hook_permission

### ISSUE THREAD

**Issue by jenlampton** [bjoern-st/wordpress_import#3]
The docblock for `hook_permission` still references the Drupal 6 `hook_perm` and the title should be formatted "Implements hook_permission()." The @return and @author lines can be removed, as per Backdrop coding standards.

```php
/**
 * hook_perm
 *
 * @return array perms
 * @author Yann Rocq
 **/
```

**Comment by bjoern-st** [comment]
@jenlampton  Fixed - pleasse see https://github.com/bjoern-st/wordpress_import/commit/b6b58148b2a32ddcb7ac7c39d6996b88dba59ff8
