### ISSUE TITLE
Properly namespace all helper functions

### ISSUE THREAD

**Issue by jenlampton** [bjoern-st/wordpress_import#4]
There are a few helper functions in this module which do not have names that start with the name of the module, for example, `get_term_id()` and `has_node_duplicate()`, and `file_directory_path()` and `curl_redir_url()`.

It is possible that these functions could conflict with other functions in Backdrop or any contrib project, so to prevent that from happening their names should be changed to begin with `wordpress_import_`.

**Comment by bjoern-st** [comment]
Yes, of course you're right @jenlampton 
But due to to my professional career I first need to get things working, 
It's on my ToDo List, but I've tested a lot last weekend and had to fix some problems first.

Bit I'll keep that in mind.

And thank you for your invitation :-) 

Best 

Bjoern

**Comment by bjoern-st** [comment]
Hey @jenlampton 

It's fixed ... please have a look at https://github.com/bjoern-st/wordpress_import/commit/dfa1584a0f8ee76781c185c90a29e38c4788a61c

Cheers Bjoern
