### ISSUE TITLE
dpm functions

### ISSUE THREAD

**Issue by keiserjb** [bjoern-st/wordpress_import#9]
I'm getting this error when I try and import a wordpress file.  

Error: Call to undefined function dpm() in wordpress_import_process_post() (line 1398 of /var/www/html/modules/wordpress_import/wordpress_import.module).

I can solve this in either of two ways.

1. I can comment out all of the dpm functions.
2. I can install and enable the devel module.

**Comment by bjoern-st** [comment]
Oh yes. Please comment that out - that shouldn't be there anyway. I'll fix that in a next release.

**Comment by keiserjb** [comment]
There is a pr for removing the functions causing the problem from several years ago.  https://github.com/backdrop-contrib/wordpress_import/pull/6  

We should probably get the release out so it doesn't fail.

**Comment by quicksketch** [comment]
We had a [session on WordPress to Backdrop migration at Backdrop LIVE](https://events.backdropcms.org/sessions/wordpress-to-backdrop) and this module was brought up as the best solution, but this issue was a huge "gotcha". This would be great to get this fixed.

**Comment by laryn** [comment]
Thanks @keiserjb, @daggerhart, @quicksketch, and @bjoern-st  -- these stray `dpm`s have been removed for the next release.
